SERVICE_LLM = "llm"
SERVICE_MEMORY = "memory"
SERVICE_OLLAMA = "ollama"
SERVICE_PROJECT = "project"

SERVICE_EVALUATOR = "evaluator"

TOOL_CALCULATOR = "calculator"
TOOL_FILES = "files"
TOOL_INTERNET = "internet"
TOOL_MEMORY = "memory"
TOOL_PYTHON = "python"

ACTION_CALCULATE = "calculate"
ACTION_CHAT = "chat"
ACTION_GENERATE_CODE = "generate_code"
ACTION_LIST_FILES = "list_files"
ACTION_RECALL = "recall"
ACTION_REMEMBER = "remember"
ACTION_RUN_PYTHON = "run_python"
ACTION_SEARCH_WEB = "search_web"
ACTION_PROJECT_SUMMARY = "project_summary"
ACTION_VERIFY = "verify"

APP_EXIT_COMMANDS = ("exit", "quit")

BUILD_SEPARATOR = "="

INTENT_CODING = "coding"
INTENT_FILES = "files"
INTENT_GENERAL = "general"
INTENT_INTERNET = "internet"
INTENT_MATH = "math"
INTENT_MEMORY = "memory"
INTENT_PYTHON = "python"
INTENT_PROJECT = "project"

GOAL_STATUS_IDLE = "idle"
GOAL_STATUS_NEW = "new"
GOAL_STATUS_ANALYZING = "analyzing"
GOAL_STATUS_PLANNING = "planning"
GOAL_STATUS_READY = "ready"
GOAL_STATUS_RUNNING = "running"
GOAL_STATUS_VERIFYING = "verifying"
GOAL_STATUS_FAILED = "failed"
GOAL_STATUS_REFLECTING = "reflecting"
GOAL_STATUS_REPLANNING = "replanning"
GOAL_STATUS_COMPLETED = "completed"

GOAL_PRIORITY_LOW = 1
GOAL_PRIORITY_NORMAL = 5
GOAL_PRIORITY_HIGH = 10
GOAL_PRIORITY_CRITICAL = 20

TASK_STATUS_PENDING = "pending"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_PAUSED = "paused"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_CANCELLED = "cancelled"

EVALUATION_SUCCESS = "success"
EVALUATION_FAILURE = "failure"
EVALUATION_PARTIAL = "partial"
EVALUATION_UNKNOWN = "unknown"

REFLECTION_STRATEGY_RETRY = "retry"
REFLECTION_STRATEGY_REPLAN = "replan"
REFLECTION_STRATEGY_ALTERNATIVE = "alternative"
REFLECTION_STRATEGY_USER = "user"
REFLECTION_STRATEGY_GIVE_UP = "give_up"

MAX_RETRY_COUNT = 2

KERNEL_STATUS_BOOTING = "Booting"
KERNEL_STATUS_ONLINE = "Online"

