from __future__ import annotations

import threading
import uuid
from typing import Any, Optional

from agents.base_agent import BaseAgent
from brain.dependency_resolver import DependencyResolver, CycleError
from brain.fleet_manager import FleetManager
from brain.messaging import Messaging, Message
from brain.mission.mission_status import MissionStatus
from brain.shared_context import SharedContext
from brain.work_pool import WorkPool


class ChiefAgent(BaseAgent):
    """Orchestrates adaptive missions using capability-aware work stealing.

    The ChiefAgent NEVER executes work itself. Instead, it delegates mission
    decomposition to a planning capability via the WorkPool. It then resolves
    sub-task dependencies and dynamically schedules execution by submitting
    ready tasks to the WorkPool.

    Uses event-driven execution via the Messaging bus to avoid polling.

    For Mission-level orchestration, :meth:`execute_mission` dispatches a
    ``MissionGraph`` to ``MissionExecutor`` while publishing lifecycle
    events through an optional ``MissionEventBus``.  Execution remains
    owned by ``MissionExecutor``; ``ChiefAgent`` only validates, dispatches,
    and reports.
    """

    def __init__(
        self,
        work_pool: WorkPool,
        dependency_resolver: DependencyResolver,
        shared_context: Optional[SharedContext] = None,
        messaging: Optional[Messaging] = None,
        fleet_manager: Optional[FleetManager] = None,
    ) -> None:
        # Reuse the WorkPool's messaging bus when no explicit bus is
        # provided.  The chief must listen on the same bus that the
        # WorkPool broadcasts task_completed/task_failed events on,
        # otherwise distributed dispatch will deadlock.
        if messaging is None:
            messaging = work_pool._messaging
        super().__init__("chief", shared_context, messaging)
        self._work_pool = work_pool
        self._resolver = dependency_resolver
        self._fleet_manager = fleet_manager

        # Synchronization for event-driven orchestration
        self._lock = threading.RLock()
        self._completion_event = threading.Event()
        self._mission_result: dict[str, Any] = {"success": False, "errors": []}

        # Mission state tracking
        self._active_mission: str = ""
        self._planning_task_id: str = ""
        self._completed_tasks: set[str] = set()
        self._pending_tasks: dict[str, dict] = {}
        self._task_results: dict[str, Any] = {}

        # Subscribe to broadcast events from the WorkPool
        self._messaging.subscribe("chief", self._on_message)

        # Register with FleetManager if provided
        if self._fleet_manager is not None:
            self._fleet_manager.register("chief", ["planning", "orchestration"])
            self._send_heartbeat(status="idle", load=0)

    def _on_message(self, message: Message) -> None:
        """Handle incoming events from the WorkPool."""
        if message.msg_type == "task_completed":
            self._handle_task_completed(message.payload or {})
        elif message.msg_type == "task_failed":
            self._handle_task_failed(message.payload or {})

    def _handle_task_completed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        result = payload.get("result", {})

        with self._lock:
            if task_id == self._planning_task_id:
                self._handle_plan_completed(result)
            elif task_id in self._pending_tasks:
                self._completed_tasks.add(task_id)
                self._task_results[task_id] = result
                del self._pending_tasks[task_id]
                self._schedule_ready_tasks()

            self._check_mission_complete()

    def _handle_task_failed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        error = payload.get("error", "Unknown error")

        with self._lock:
            if task_id == self._planning_task_id or task_id in self._pending_tasks:
                self._mission_result = {"success": False, "errors": [error]}
                self._completion_event.set()

    def _handle_plan_completed(self, result: Any) -> None:
        """Process the mission decomposition generated by a planner agent."""
        # Normalize result to a list of task dicts
        tasks = result.get("tasks", []) if isinstance(result, dict) else result
        if not isinstance(tasks, list):
            self._mission_result = {"success": False, "errors": ["Invalid decomposition plan format"]}
            self._completion_event.set()
            return

        try:
            # Validate DAG and determine topological order
            ordered_tasks = self._resolver.resolve(tasks)
        except (CycleError, ValueError) as e:
            self._mission_result = {"success": False, "errors": [str(e)]}
            self._completion_event.set()
            return

        for t in ordered_tasks:
            # Ensure unique internal state status
            t["_sched_status"] = "waiting"
            self._pending_tasks[t["id"]] = t

        self._completed_tasks.add(self._planning_task_id)
        self._schedule_ready_tasks()

    def _schedule_ready_tasks(self) -> None:
        """Submit tasks to the WorkPool whose dependencies have been satisfied."""
        with self._lock:
            self._schedule_ready_tasks_locked()

    def _schedule_ready_tasks_locked(self) -> None:
        """Inner variant of _schedule_ready_tasks — caller must hold ``_lock``."""
        to_submit = []
        for task_id, task in self._pending_tasks.items():
            if task.get("_sched_status") == "submitted":
                continue

            deps = task.get("depends_on", [])
            # A task is ready if all dependencies are in the completed set
            if all(dep in self._completed_tasks for dep in deps):
                to_submit.append(task)

        for task in to_submit:
            task["_sched_status"] = "submitted"
            cap = task.get("required_capability", "llm")
            self._work_pool.submit_task(task, cap)

    def _check_mission_complete(self) -> None:
        """Trigger mission completion if all tasks have finished."""
        if not self._pending_tasks:
            # All pending tasks done. Check if planning phase is also done (or was skipped).
            if not self._planning_task_id or self._planning_task_id in self._completed_tasks:
                self._mission_result = {"success": True, "errors": []}
                self._completion_event.set()

    def _send_heartbeat(self, status: str, load: int = 0) -> None:
        """Send a heartbeat to the FleetManager if available."""
        if self._fleet_manager is not None:
            try:
                self._fleet_manager.report_health("chief", {"status": status, "load": load})
            except Exception:
                pass  # Heartbeat failures must not break execution

    def run(self, shared_context: SharedContext) -> dict:
        """Execute a mission orchestration (blocks until completion)."""
        task = shared_context.get("task")
        if not task:
            error = "No task provided in shared context"
            self._logger.error(error)
            return {"success": False, "errors": [error]}

        self._status = "running"
        self._active_mission = task
        self._planning_task_id = str(uuid.uuid4())

        with self._lock:
            self._completed_tasks.clear()
            self._pending_tasks.clear()
            self._mission_result = {"success": False, "errors": []}
            self._completion_event.clear()

        # Submit decomposition task to the planning capability
        plan_task = {
            "id": self._planning_task_id,
            "action": "plan",
            "data": task,
        }
        self._logger.info("chief delegating mission decomposition", task_id=self._planning_task_id)
        self._work_pool.submit_task(plan_task, "planner")

        # Event-driven wait (no continuous polling loop)
        self._completion_event.wait()

        self._status = "completed" if self._mission_result["success"] else "failed"
        return self._mission_result

    def execute_mission(
        self,
        graph: Any,
        event_bus: Optional[Any] = None,
        timeout: float = 300.0,
        force_sequential: bool = False,
    ) -> dict[str, Any]:
        """Orchestrate execution of a ``MissionGraph``.

        When a ``FleetManager`` is available, missions are submitted to the
        ``WorkPool`` for distributed execution by agents that steal work
        matching their capabilities.  When no fleet is present (or
        ``force_sequential`` is ``True``), the graph is executed
        sequentially via ``MissionExecutor``.

        In both paths ``MissionExecutor`` remains the execution owner;
        ``ChiefAgent`` only validates, dispatches, and reports.

        Args:
            graph: A ``MissionGraph`` of missions to execute.
            event_bus: Optional ``MissionEventBus`` for lifecycle
                notifications (MISSION_STARTED, MISSION_COMPLETED,
                MISSION_FAILED).
            timeout: Maximum seconds to wait for distributed execution
                completion.  Ignored in the sequential path.  Defaults
                to 300 seconds (5 minutes).
            force_sequential: If ``True``, always use the sequential
                path even when a ``FleetManager`` is attached.  Useful
                for testing heartbeat behavior without distributed
                dispatch.

        Returns:
            Dictionary with ``success``, ``results`` (per-mission dict),
            ``executed`` count, ``skipped`` count, and ``errors`` list.
        """
        self._status = "running"
        self._logger.info("chief executing mission graph", mission_count=len(graph))

        # Validate graph via Planner (reuse existing planning logic)
        try:
            from brain.planner.planner import Planner
            planner = Planner()
            plan = planner.plan_missions(graph)
        except ValueError as e:
            self._logger.error("mission graph validation failed", error=str(e))
            self._status = "failed"
            return {"success": False, "errors": [str(e)], "executed": 0, "skipped": 0, "results": {}}

        mission_count = len(plan)
        self._logger.info("chief missions planned", plan_size=mission_count)

        # Send heartbeat: mission execution starting
        self._send_heartbeat(status="running", load=mission_count)

        # Publish pre-execution events for each executable mission via
        # the optional event bus so external observers can track progress.
        if event_bus is not None and hasattr(event_bus, "publish"):
            try:
                from brain.mission.event import MissionEvent
                from brain.mission.event_types import MissionEventType
            except ImportError:
                pass
            else:
                for mission in plan:
                    event_bus.publish(MissionEvent(
                        mission_id=str(mission.id),
                        event_type=MissionEventType.MISSION_STATUS_CHANGED,
                        payload={
                            "old_status": mission.status.value,
                            "new_status": "dispatched",
                        },
                    ))

        # Attach event bus to missions so external agents publish lifecycle
        # events during distributed execution.
        if event_bus is not None:
            for mission in plan:
                mission.event_bus = event_bus

        if self._fleet_manager is None or force_sequential:
            # Sequential fallback — no fleet available or forced.
            result = self._execute_sequential(graph)
        else:
            # Distributed path — delegate ready missions to WorkPool.
            result = self._execute_distributed(plan, graph, timeout=timeout)

        # Publish terminal events for each executed mission.
        if event_bus is not None and hasattr(event_bus, "publish"):
            try:
                from brain.mission.event import MissionEvent
                from brain.mission.event_types import MissionEventType
            except ImportError:
                pass
            else:
                for mission in plan:
                    if mission.status.is_terminal():
                        event_type = (
                            MissionEventType.MISSION_COMPLETED
                            if mission.status.value == "completed"
                            else MissionEventType.MISSION_FAILED
                        )
                        event_bus.publish(MissionEvent(
                            mission_id=str(mission.id),
                            event_type=event_type,
                            payload={"status": mission.status.value},
                        ))

        self._logger.info(
            "chief mission execution complete",
            success=result.get("success"),
            executed=result.get("executed", 0),
        )

        errors: list[str] = []
        if not result.get("success"):
            # MissionExecutor may return "error" (str) or "errors" (list).
            raw_errors = result.get("errors", [])
            if raw_errors:
                if isinstance(raw_errors, list):
                    errors.extend(raw_errors)
                else:
                    errors.append(str(raw_errors))
            single_error = result.get("error")
            if single_error:
                errors.append(str(single_error))
            if not errors:
                errors.append("Mission execution failed")

        self._status = "completed" if result.get("success") else "failed"

        # Send final heartbeat
        self._send_heartbeat(
            status=self._status,
            load=0,
        )

        return {
            "success": result.get("success", False),
            "results": result.get("results", {}),
            "executed": result.get("executed", 0),
            "skipped": result.get("skipped", 0),
            "errors": errors,
        }

    def _execute_sequential(self, graph: Any) -> dict[str, Any]:
        """Execute a MissionGraph sequentially via MissionExecutor.

        This is the fallback path when no ``FleetManager`` is available.
        """
        try:
            from brain.mission.mission_executor import MissionExecutor
            executor = MissionExecutor()
            return executor.execute(graph)
        except Exception as e:
            self._logger.error("mission executor failed", error=str(e))
            return {
                "success": False,
                "errors": [str(e)],
                "executed": 0,
                "skipped": 0,
                "results": {},
            }

    def _execute_distributed(
        self,
        plan: list[Any],
        graph: Any,
        timeout: float = 300.0,
    ) -> dict[str, Any]:
        """Execute planned missions via the WorkPool.

        Missions are converted to task dicts and submitted to the WorkPool.
        Agents steal tasks by capability, execute via ``MissionExecutor``,
        and report completion through the messaging bus.  Dependencies are
        respected through the existing ``_schedule_ready_tasks`` gating.

        A bounded ``timeout`` prevents indefinite hangs when no worker
        picks up a task or a worker dies silently.  On timeout the
        ChiefAgent reports a graceful failure rather than deadlocking.

        Args:
            plan: List of ``Mission`` objects to dispatch.
            graph: The source ``MissionGraph`` — used for dependency
                resolution since ``mission.dependencies`` is a separate
                dataclass field from graph edges.
            timeout: Maximum seconds to wait for completion.  Defaults
                to 300 seconds (5 minutes) per Mission 7.1.6 graceful
                shutdown requirements.

        Returns:
            Dictionary with ``success``, ``errors``, ``executed``,
            ``skipped``, and ``results`` keys.
        """
        from brain.capability_router import CapabilityRouter

        router = CapabilityRouter()

        with self._lock:
            self._completed_tasks.clear()
            self._pending_tasks.clear()
            self._task_results.clear()
            self._mission_result = {"success": False, "errors": []}
            self._completion_event.clear()
            self._planning_task_id = ""  # No planning phase for direct dispatch

            for mission in plan:
                # Infer capability from mission content via existing router.
                inferred = router.route(
                    {"action": "execute_mission", "data": mission.description}
                )
                # Resolve dependencies from the graph, not the mission's
                # ``dependencies`` dataclass field (which is populated by
                # ``Mission.add_dependency()``, not ``MissionGraph.add_dependency()``).
                dep_missions = graph.get_dependencies(mission)
                depends_on = [str(d.id) for d in dep_missions]
                task = {
                    "id": str(mission.id),
                    "action": "execute_mission",
                    "data": mission,
                    "depends_on": depends_on,
                    "_sched_status": "waiting",
                    "required_capability": inferred,
                }
                self._pending_tasks[str(mission.id)] = task

            self._schedule_ready_tasks_locked()

        # Bounded wait — graceful shutdown on timeout instead of deadlock.
        completed = self._completion_event.wait(timeout=timeout)

        if not completed:
            # Timeout — report remaining pending tasks as failed.
            with self._lock:
                timed_out = list(self._pending_tasks.keys())
                for tid in timed_out:
                    self._pending_tasks.pop(tid, None)
            self._logger.warning(
                "distributed execution timed out",
                timeout=timeout,
                pending=timed_out,
            )
            return {
                "success": False,
                "errors": [f"Execution timed out after {timeout}s: {timed_out}"],
                "executed": sum(1 for m in plan if m.status.is_terminal()),
                "skipped": len(plan) - sum(1 for m in plan if m.status.is_terminal()),
                "results": self._task_results,
            }

        executed = sum(
            1 for m in plan if m.status.is_terminal()
        )
        skipped = len(plan) - executed
        success = all(m.status == MissionStatus.COMPLETED for m in plan)
        errors = [
            m.error for m in plan
            if m.status == MissionStatus.FAILED and m.error
        ]

        return {
            "success": success,
            "errors": errors,
            "executed": executed,
            "skipped": skipped,
            "results": self._task_results,
        }
