from __future__ import annotations

import threading
import uuid
from typing import Any, Optional

from agents.base_agent import BaseAgent
from brain.dependency_resolver import DependencyResolver, CycleError
from brain.messaging import Messaging, Message
from brain.shared_context import SharedContext
from brain.work_pool import WorkPool


class ChiefAgent(BaseAgent):
    """Orchestrates adaptive missions using capability-aware work stealing.

    The ChiefAgent NEVER executes work itself. Instead, it delegates mission
    decomposition to a planning capability via the WorkPool. It then resolves
    sub-task dependencies and dynamically schedules execution by submitting
    ready tasks to the WorkPool.

    Uses event-driven execution via the Messaging bus to avoid polling.
    """

    def __init__(
        self,
        work_pool: WorkPool,
        dependency_resolver: DependencyResolver,
        shared_context: Optional[SharedContext] = None,
        messaging: Optional[Messaging] = None,
    ) -> None:
        super().__init__("chief", shared_context, messaging)
        self._work_pool = work_pool
        self._resolver = dependency_resolver

        # Synchronization for event-driven orchestration
        self._lock = threading.RLock()
        self._completion_event = threading.Event()
        self._mission_result: dict[str, Any] = {"success": False, "errors": []}

        # Mission state tracking
        self._active_mission: str = ""
        self._planning_task_id: str = ""
        self._completed_tasks: set[str] = set()
        self._pending_tasks: dict[str, dict] = {}

        # Subscribe to broadcast events from the WorkPool
        self._messaging.subscribe("chief", self._on_message)

    def _on_message(self, message: Message) -> None:
        """Handle incoming events from the WorkPool."""
        if message.msg_type == "task_completed":
            self._handle_task_completed(message.payload or {})
        elif message.msg_type == "task_failed":
            self._handle_task_failed(message.payload or {})

    def _handle_task_completed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        result = payload.get("result", {})

        with self._lock:
            if task_id == self._planning_task_id:
                self._handle_plan_completed(result)
            elif task_id in self._pending_tasks:
                self._completed_tasks.add(task_id)
                del self._pending_tasks[task_id]
                self._schedule_ready_tasks()

            self._check_mission_complete()

    def _handle_task_failed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        error = payload.get("error", "Unknown error")

        with self._lock:
            if task_id == self._planning_task_id or task_id in self._pending_tasks:
                self._mission_result = {"success": False, "errors": [error]}
                self._completion_event.set()

    def _handle_plan_completed(self, result: Any) -> None:
        """Process the mission decomposition generated by a planner agent."""
        # Normalize result to a list of task dicts
        tasks = result.get("tasks", []) if isinstance(result, dict) else result
        if not isinstance(tasks, list):
            self._mission_result = {"success": False, "errors": ["Invalid decomposition plan format"]}
            self._completion_event.set()
            return

        try:
            # Validate DAG and determine topological order
            ordered_tasks = self._resolver.resolve(tasks)
        except (CycleError, ValueError) as e:
            self._mission_result = {"success": False, "errors": [str(e)]}
            self._completion_event.set()
            return

        for t in ordered_tasks:
            # Ensure unique internal state status
            t["_sched_status"] = "waiting"
            self._pending_tasks[t["id"]] = t

        self._completed_tasks.add(self._planning_task_id)
        self._schedule_ready_tasks()

    def _schedule_ready_tasks(self) -> None:
        """Submit tasks to the WorkPool whose dependencies have been satisfied."""
        to_submit = []
        for task_id, task in self._pending_tasks.items():
            if task.get("_sched_status") == "submitted":
                continue

            deps = task.get("depends_on", [])
            # A task is ready if all dependencies are in the completed set
            if all(dep in self._completed_tasks for dep in deps):
                to_submit.append(task)

        for task in to_submit:
            task["_sched_status"] = "submitted"
            cap = task.get("required_capability", "llm")
            self._work_pool.submit_task(task, cap)

    def _check_mission_complete(self) -> None:
        """Trigger mission completion if all tasks have finished."""
        if not self._pending_tasks and self._planning_task_id in self._completed_tasks:
            self._mission_result = {"success": True, "errors": []}
            self._completion_event.set()

    def run(self, shared_context: SharedContext) -> dict:
        """Execute a mission orchestration (blocks until completion)."""
        task = shared_context.get("task")
        if not task:
            error = "No task provided in shared context"
            self._logger.error(error)
            return {"success": False, "errors": [error]}

        self._status = "running"
        self._active_mission = task
        self._planning_task_id = str(uuid.uuid4())

        with self._lock:
            self._completed_tasks.clear()
            self._pending_tasks.clear()
            self._mission_result = {"success": False, "errors": []}
            self._completion_event.clear()

        # Submit decomposition task to the planning capability
        plan_task = {
            "id": self._planning_task_id,
            "action": "plan",
            "data": task,
        }
        self._logger.info("chief delegating mission decomposition", task_id=self._planning_task_id)
        self._work_pool.submit_task(plan_task, "planner")

        # Event-driven wait (no continuous polling loop)
        self._completion_event.wait()

        self._status = "completed" if self._mission_result["success"] else "failed"
        return self._mission_result
