from __future__ import annotations

import threading
import uuid
from typing import Any, Optional

from agents.base_agent import BaseAgent
from brain.dependency_resolver import DependencyResolver, CycleError
from brain.fleet_manager import FleetManager
from brain.messaging import Messaging, Message
from brain.shared_context import SharedContext
from brain.work_pool import WorkPool


class ChiefAgent(BaseAgent):
    """Orchestrates adaptive missions using capability-aware work stealing.

    The ChiefAgent NEVER executes work itself. Instead, it delegates mission
    decomposition to a planning capability via the WorkPool. It then resolves
    sub-task dependencies and dynamically schedules execution by submitting
    ready tasks to the WorkPool.

    Uses event-driven execution via the Messaging bus to avoid polling.

    For Mission-level orchestration, :meth:`execute_mission` dispatches a
    ``MissionGraph`` to ``MissionExecutor`` while publishing lifecycle
    events through an optional ``MissionEventBus``.  Execution remains
    owned by ``MissionExecutor``; ``ChiefAgent`` only validates, dispatches,
    and reports.
    """

    def __init__(
        self,
        work_pool: WorkPool,
        dependency_resolver: DependencyResolver,
        shared_context: Optional[SharedContext] = None,
        messaging: Optional[Messaging] = None,
        fleet_manager: Optional[FleetManager] = None,
    ) -> None:
        super().__init__("chief", shared_context, messaging)
        self._work_pool = work_pool
        self._resolver = dependency_resolver
        self._fleet_manager = fleet_manager

        # Synchronization for event-driven orchestration
        self._lock = threading.RLock()
        self._completion_event = threading.Event()
        self._mission_result: dict[str, Any] = {"success": False, "errors": []}

        # Mission state tracking
        self._active_mission: str = ""
        self._planning_task_id: str = ""
        self._completed_tasks: set[str] = set()
        self._pending_tasks: dict[str, dict] = {}

        # Subscribe to broadcast events from the WorkPool
        self._messaging.subscribe("chief", self._on_message)

        # Register with FleetManager if provided
        if self._fleet_manager is not None:
            self._fleet_manager.register("chief", ["planning", "orchestration"])
            self._send_heartbeat(status="idle", load=0)

    def _on_message(self, message: Message) -> None:
        """Handle incoming events from the WorkPool."""
        if message.msg_type == "task_completed":
            self._handle_task_completed(message.payload or {})
        elif message.msg_type == "task_failed":
            self._handle_task_failed(message.payload or {})

    def _handle_task_completed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        result = payload.get("result", {})

        with self._lock:
            if task_id == self._planning_task_id:
                self._handle_plan_completed(result)
            elif task_id in self._pending_tasks:
                self._completed_tasks.add(task_id)
                del self._pending_tasks[task_id]
                self._schedule_ready_tasks()

            self._check_mission_complete()

    def _handle_task_failed(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        error = payload.get("error", "Unknown error")

        with self._lock:
            if task_id == self._planning_task_id or task_id in self._pending_tasks:
                self._mission_result = {"success": False, "errors": [error]}
                self._completion_event.set()

    def _handle_plan_completed(self, result: Any) -> None:
        """Process the mission decomposition generated by a planner agent."""
        # Normalize result to a list of task dicts
        tasks = result.get("tasks", []) if isinstance(result, dict) else result
        if not isinstance(tasks, list):
            self._mission_result = {"success": False, "errors": ["Invalid decomposition plan format"]}
            self._completion_event.set()
            return

        try:
            # Validate DAG and determine topological order
            ordered_tasks = self._resolver.resolve(tasks)
        except (CycleError, ValueError) as e:
            self._mission_result = {"success": False, "errors": [str(e)]}
            self._completion_event.set()
            return

        for t in ordered_tasks:
            # Ensure unique internal state status
            t["_sched_status"] = "waiting"
            self._pending_tasks[t["id"]] = t

        self._completed_tasks.add(self._planning_task_id)
        self._schedule_ready_tasks()

    def _schedule_ready_tasks(self) -> None:
        """Submit tasks to the WorkPool whose dependencies have been satisfied."""
        to_submit = []
        for task_id, task in self._pending_tasks.items():
            if task.get("_sched_status") == "submitted":
                continue

            deps = task.get("depends_on", [])
            # A task is ready if all dependencies are in the completed set
            if all(dep in self._completed_tasks for dep in deps):
                to_submit.append(task)

        for task in to_submit:
            task["_sched_status"] = "submitted"
            cap = task.get("required_capability", "llm")
            self._work_pool.submit_task(task, cap)

    def _check_mission_complete(self) -> None:
        """Trigger mission completion if all tasks have finished."""
        if not self._pending_tasks and self._planning_task_id in self._completed_tasks:
            self._mission_result = {"success": True, "errors": []}
            self._completion_event.set()

    def _send_heartbeat(self, status: str, load: int = 0) -> None:
        """Send a heartbeat to the FleetManager if available."""
        if self._fleet_manager is not None:
            try:
                self._fleet_manager.report_health("chief", {"status": status, "load": load})
            except Exception:
                pass  # Heartbeat failures must not break execution

    def run(self, shared_context: SharedContext) -> dict:
        """Execute a mission orchestration (blocks until completion)."""
        task = shared_context.get("task")
        if not task:
            error = "No task provided in shared context"
            self._logger.error(error)
            return {"success": False, "errors": [error]}

        self._status = "running"
        self._active_mission = task
        self._planning_task_id = str(uuid.uuid4())

        with self._lock:
            self._completed_tasks.clear()
            self._pending_tasks.clear()
            self._mission_result = {"success": False, "errors": []}
            self._completion_event.clear()

        # Submit decomposition task to the planning capability
        plan_task = {
            "id": self._planning_task_id,
            "action": "plan",
            "data": task,
        }
        self._logger.info("chief delegating mission decomposition", task_id=self._planning_task_id)
        self._work_pool.submit_task(plan_task, "planner")

        # Event-driven wait (no continuous polling loop)
        self._completion_event.wait()

        self._status = "completed" if self._mission_result["success"] else "failed"
        return self._mission_result

    def execute_mission(
        self,
        graph: Any,
        event_bus: Optional[Any] = None,
    ) -> dict[str, Any]:
        """Orchestrate execution of a ``MissionGraph`` through ``MissionExecutor``.

        The ChiefAgent validates and dispatches the graph to the existing
        ``MissionExecutor``, which owns the actual execution path
        (MissionExecutor → AutonomousExecutor → Kernel → Tools).  An
        optional ``MissionEventBus`` receives lifecycle events as missions
        progress.

        This method is additive — the existing ``run(ctx)`` WorkPool-based
        pipeline continues to work unchanged.  ChiefAgent does NOT replace
        or duplicate ``MissionExecutor`` execution logic.

        Args:
            graph: A ``MissionGraph`` of missions to execute.
            event_bus: Optional ``MissionEventBus`` for lifecycle
                notifications (MISSION_STARTED, MISSION_COMPLETED,
                MISSION_FAILED).

        Returns:
            Dictionary with ``success``, ``results`` (per-mission dict),
            ``executed`` count, ``skipped`` count, and ``errors`` list.
        """
        self._status = "running"
        self._logger.info("chief executing mission graph", mission_count=len(graph))

        # Validate graph via Planner (reuse existing planning logic)
        try:
            from brain.planner.planner import Planner
            planner = Planner()
            plan = planner.plan_missions(graph)
        except ValueError as e:
            self._logger.error("mission graph validation failed", error=str(e))
            self._status = "failed"
            return {"success": False, "errors": [str(e)], "executed": 0, "skipped": 0, "results": {}}

        mission_count = len(plan)
        self._logger.info("chief missions planned", plan_size=mission_count)

        # Send heartbeat: mission execution starting
        self._send_heartbeat(status="running", load=mission_count)

        # Publish pre-execution events for each executable mission via
        # the optional event bus so external observers can track progress.
        if event_bus is not None and hasattr(event_bus, "publish"):
            try:
                from brain.mission.event import MissionEvent
                from brain.mission.event_types import MissionEventType
            except ImportError:
                pass
            else:
                for mission in plan:
                    event_bus.publish(MissionEvent(
                        mission_id=str(mission.id),
                        event_type=MissionEventType.MISSION_STATUS_CHANGED,
                        payload={
                            "old_status": mission.status.value,
                            "new_status": "dispatched",
                        },
                    ))

        # Delegate execution to MissionExecutor — ChiefAgent orchestrates,
        # MissionExecutor executes.
        try:
            from brain.mission.mission_executor import MissionExecutor
            executor = MissionExecutor()
            result = executor.execute(graph)
        except Exception as e:
            self._logger.error("mission executor failed", error=str(e))
            self._status = "failed"
            return {"success": False, "errors": [str(e)], "executed": 0, "skipped": 0, "results": {}}

        # Publish terminal events for each executed mission.
        if event_bus is not None and hasattr(event_bus, "publish"):
            try:
                from brain.mission.event import MissionEvent
                from brain.mission.event_types import MissionEventType
            except ImportError:
                pass
            else:
                for mission in plan:
                    if mission.status.is_terminal():
                        event_type = (
                            MissionEventType.MISSION_COMPLETED
                            if mission.status.value == "completed"
                            else MissionEventType.MISSION_FAILED
                        )
                        event_bus.publish(MissionEvent(
                            mission_id=str(mission.id),
                            event_type=event_type,
                            payload={"status": mission.status.value},
                        ))

        self._logger.info(
            "chief mission execution complete",
            success=result.get("success"),
            executed=result.get("executed", 0),
        )

        errors = []
        if not result.get("success"):
            errors.append(result.get("error", "Mission execution failed"))

        self._status = "completed" if result.get("success") else "failed"

        # Send final heartbeat
        self._send_heartbeat(
            status=self._status,
            load=0,
        )

        return {
            "success": result.get("success", False),
            "results": result.get("results", {}),
            "executed": result.get("executed", 0),
            "skipped": result.get("skipped", 0),
            "errors": errors,
        }
